### ISSUE TITLE
Default options not working

### ISSUE THREAD

**Issue by andyjamesn** [storyblok/field-plugin#390]
**Describe the bug**
Created a Vue field plugin using monorepo with the cli

**To Reproduce**
Ass simple starter field to log the options

Add options to field-plugin.config.json

```
<script setup lang="ts">
import { useFieldPlugin } from '@storyblok/field-plugin/vue3';

const plugin = useFieldPlugin()

console.log(plugin);
</script>
```

```
{
  "options": [
    {
      "name": "option",
      "value": "value"
    }
  ]
}
```
**Expected behavior**
Expect to log the options but it is emty

**Screenshots**
![CleanShot 2024-05-28 at 13 40 53@2x](https://github.com/storyblok/field-plugin/assets/54320410/e580937d-955b-437e-879f-94f88dedea3f)

**Desktop (please complete the following information):**
 - OS: mac 14.3
 - Browser chrome
 - Version 124

**Additional context**
Using the sandbox I also see no default options are set

**Comment by demetriusfeijoo** [comment]
Hey @andyjamesn 👋 , 
thanks for reaching out to us and for all the provided details.

Since a field plugin is embedded within an iframe, all communication between the plugin and the container (such as the Sandbox) is done asynchronously. This means that if you try to access the data property right after calling the useFieldPlugin helper, it won't return anything.

The plugin needs to wait for the container to send the data back before it can use it. To determine when all the data is ready, you can check the `plugin.type` property to see if its value is `loaded`.

So, I would suggest you try the following approach which I think may fix the issue:

```js
const plugin = useFieldPlugin()

watch(
  () => plugin.type,
  (type) => {
    if (type === 'loaded') { // make sure to access the data only after the plugin is correctly loaded.
      console.log('options', plugin.data?.options)
    }
  },
)
```

Let me know if it helped you 🙌
